# Look at https://alacritty.org/config-alacritty.html

[general]
import = []
working_directory = "None"
live_config_reload = true

[window]
dimensions = { columns = 0, lines = 0 }
padding = { x = 0, y = 0 }
decorations = "full"
startup_mode = "Maximized"
opacity = 1.0
dynamic_title = true
dynamic_padding = false
decorations_theme_variant = "None"

[scrolling]
history = 10000
multiplier = 3

[font]
size = 14.0
offset = { x = 0, y = 0 }
glyph_offset = { x = 0, y = 0 }

[colors]
indexed_colors = [
    { index = 16, color = "0xd08770" },
    { index = 17, color = "0xab7967" },
    { index = 18, color = "0x343d46" },
    { index = 19, color = "0x4f5b66" },
    { index = 20, color = "0xa7adba" },
    { index = 21, color = "0xdfe1e8" }
]

[colors.primary]
background = "0x2b303b"
foreground = "0xc0c5ce"

[colors.cursor]
text = "0x2b303b"
cursor = "0xc0c5ce"

[colors.normal]
black   = "0x2b303b"
red     = "0xbf616a"
green   = "0xa3be8c"
yellow  = "0xebcb8b"
blue    = "0x8fa1b3"
magenta = "0xb48ead"
cyan    = "0x96b5b4"
white   = "0xc0c5ce"

[colors.bright]
black   = "0x65737e"
red     = "0xbf616a"
green   = "0xa3be8c"
yellow  = "0xebcb8b"
blue    = "0x8fa1b3"
magenta = "0xb48ead"
cyan    = "0x96b5b4"
white   = "0xeff1f5"

[bell]
animation = "EaseOutExpo"
duration = 0
color = "0xffffff"

[selection]
semantic_escape_chars = ",â”‚`|:\"' ()[]{}<>\t"
save_to_clipboard = false

[cursor]
style = "Block"
unfocused_hollow = true

[mouse]
hide_when_typing = false
bindings = [
    { mouse = "Right", action = "Paste" }
]

[debug]
render_timer = false
persistent_logging = false
log_level = "Warn"
renderer = "None"
print_events = false

[keyboard]
bindings = [
    { key = "C", mods = "Control | Shift", action = "Copy" },
    { key = "V", mods = "Control | Shift", action = "Paste" },
    { key = "L", mods = "Control", action = "ClearLogNotice" },
]
